"""empty message

Revision ID: 369a05049a87
Revises: d881f28a7c3c
Create Date: 2018-12-09 13:29:33.637247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '369a05049a87'
down_revision = 'd881f28a7c3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
