"""empty message

Revision ID: 5b8bf82a38d6
Revises: cc401fea4b7d
Create Date: 2018-12-22 17:06:16.589765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b8bf82a38d6'
down_revision = 'cc401fea4b7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('posts', 'body_html')
    # op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    # op.drop_column('posts', 'body_heml')
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_heml', sa.TEXT(), nullable=True))
    op.drop_column('posts', 'body_html')
    # ### end Alembic commands ###
