"""empty message

Revision ID: 9e2a315a34f7
Revises: b42d52064850
Create Date: 2018-12-22 21:12:02.195808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e2a315a34f7'
down_revision = 'b42d52064850'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('posts',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('body', sa.Text(), nullable=True),
    # sa.Column('body_html', sa.Text(), nullable=True),
    # sa.Column('timestamp', sa.DateTime(), nullable=True),
    # sa.Column('author_id', sa.Integer(), nullable=True),
    # sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_index(op.f('ix_posts_timestamp'), 'posts', ['timestamp'], unique=False)
    # op.drop_index('ix_posts_timestamp', table_name='posts_temp')
    op.drop_table('posts_temp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts_temp',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('body', sa.TEXT(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('author_id', sa.INTEGER(), nullable=True),
    sa.Column('body_heml', sa.TEXT(), nullable=True),
    sa.Column('body_html', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_posts_timestamp', 'posts_temp', ['timestamp'], unique=False)
    op.drop_index(op.f('ix_posts_timestamp'), table_name='posts')
    op.drop_table('posts')
    # ### end Alembic commands ###
