"""empty message

Revision ID: b42d52064850
Revises: 5b8bf82a38d6
Create Date: 2018-12-22 17:15:24.491538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b42d52064850'
down_revision = '5b8bf82a38d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('posts', 'body_heml')
    # ### end Alembic commands ###
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_heml', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###
